### PR TITLE
Development team list

### PR DESCRIPTION
**Pull request by jackylaucf**
development team list updated with email and roles listed

### CODE REVIEW

**Comment by koman2019** [comment]
nice accordion, nice photo and nice description.

**Comment by samlee0126** [comment]
It looks great. The animation is smooth. Just wonder if the red diamond icon replaced by a dog emoji, will it be better?

**Comment by koman2019** [comment]
@samlee0126 
agree.. may be put this change to our enhancement list because our designer may be busy now
btw, why what i see is black diamond lol

**Comment by samlee0126** [comment]
Maybe because I used Safari on my phone to see lol

**Pull request merged**
