### PR TITLE
wrap up all html page and enhance the feedback form

### PR DESCRIPTION
**Pull request by koman2019**
add some image (downloaded from internet) to enhance the layout
change some font style and size
feedback form enhancement
event list created

### CODE REVIEW

**Comment by samlee0126** [comment]
I think the style of the feedback form is a little bit odd. Maybe the color scheme or the font should have some adjustment.
Also, for the popular events, the images are tilted, which should be modified into filling the frame.

**Comment by koman2019** [comment]
ok. let me change the style of feedback form
the images are titled because the demo image is very small i think..

**Comment by jackylaucf** [comment]
ya the image size is quite small (170x170px), but i guess add padding will be fine to solve that

**Comment by koman2019** [comment]
Let me change the image to be one bigger image for demo.

**Pull request merged**
