### PR TITLE
Leader layout

### PR DESCRIPTION
**Pull request by s07s1174s**

### CODE REVIEW

**Comment by ChromiumIV** [comment]
The logo is quite good: it is clean and stands out with high contrast. But the background of the logo and nav bar are both in dark color, this requires some changes.
The layout is organized and clear. Just need adjustments on the column widths.
The code is good: well-structured.

**Comment by koman2019** [comment]
agree with @ChromiumIV . Lets put the change into our enhancement list first
I love the layout because it is very user-friendly.

**Comment by jackylaucf** [comment]
nice layout. one point to note: the footer shift up when clicking the options

**Comment by samlee0126** [comment]
Nice layout design. The new one is more user friendly and functional. But it is better to have a button which bring the user back to the front of the leader page and let them to add or modify password.

**Comment by koman2019** [comment]
okay . time to merge it

**Pull request merged**
